### <mark> copy and view

copy()

    -if change in one, No change in other

view()

    -creates a reference of existing array
    -if change in one, there is change in other

In [2]:
import numpy as np
v=np.array([1,2,3])
c=np.copy(v)
c

array([1, 2, 3])

In [3]:
c[0]=99
print("c", c)
print("v", v)

c [99  2  3]
v [1 2 3]


In [4]:
v=np.array([1,2,3])
c=v.view()
c

array([1, 2, 3])

In [5]:
c[0]=99
print("c", c)
print("v", v)

c [99  2  3]
v [99  2  3]


In [6]:
v[1]=0
print("c", c)
print("v", v)

c [99  0  3]
v [99  0  3]


## <mark> Filter using np.where
    
    where(condition, [x, y], /)

    returns: An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.
    
    x and y needs to be of same shape
    
    you can use broadcast value also

In [70]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [2]:
import numpy as np
arr = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [51]:
# np.where: Returns element's index depending on `condition`.
np.where(arr>5)

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [52]:
a = np.arange(10)
np.where(a < 5, a, 10*a)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [48]:
p=np.array([11,21,31,41,51])
x=np.where(p>23)
x

(array([2, 3, 4], dtype=int64),)

In [3]:
p=np.array([11, 21, 311, 411, 511])
q=np.array([13, 24, 20, 44, 66])
x=np.where(p<23, p, q)
x

# p and q needs to be of same shape

array([11, 21, 20, 44, 66])

In [61]:
a = np.array([[0, 1, 2],
               [0, 2, 4],
               [0, 3, 6]])

np.where(a < 4, a, -1)  # -1 is broadcast

array([[ 0,  1,  2],
       [ 0,  2, -1],
       [ 0,  3, -1]])

In [60]:
a=np.array([66,65,67,61,60,69])
b=np.where(a<65)
print("b: ",b)

c=a[np.where(a<65)]
print("c: ",c)

b:  (array([3, 4], dtype=int64),)
c:  [61 60]


In [62]:
# finding the index of the value

a = numpy.array([1, 2, 3, 4, 5])

print("5 is found at index: ", numpy.where(a == 5))
print(numpy.where(a == 5)[0])

5 is found at index:  (array([4], dtype=int64),)
[4]


In [ ]:
abc=np.arange(100,120,2)
print('abc: ', abc)

xyz=np.arange(1,20,1)
x=np.where(abc%2==0)
print('indices: ',x)

print('Filtered new array:\n', np.array(abc[x]))

##### <mark> searching arrays for a particular value

In [71]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4,6,7,8,9,10])

x = np.where(arr == 4)
print("4 is found at index: ",x)

x = np.where(arr%2 == 0)
print("Even are found at index: ",x)

4 is found at index:  (array([3, 5, 6], dtype=int64),)
Even are found at index:  (array([ 1,  3,  5,  6,  7,  9, 11], dtype=int64),)


In [72]:
"""searchsorted()
There is a method called searchsorted() which performs a binary search in the array, 
and returns the index where the specified value would be inserted to maintain the search order.
The searchsorted() method is assumed to be used on sorted arrays.
"""

#Find the indexes where the value 7 should be inserted:
arr = np.array([6, 7, 8, 9])
print(arr)
x = np.searchsorted(arr, 10)
print(x)
print(np.insert(arr,x,10))

[6 7 8 9]
4
[ 6  7  8  9 10]


In [73]:
#Find the indexes where the value 7 should be inserted, starting from the right:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print(x)

2


In [74]:
#Multiple values: Find the indexes where the values 2, 4, and 6 should be inserted:
arr = np.array([1, 3, 5, 7])
print(arr)
x = np.searchsorted(arr, [2, 4, 6])
print("insert at:",x)
print(np.insert(arr,x,[2, 4, 6]))

[1 3 5 7]
insert at: [1 2 3]
[1 2 3 4 5 6 7]


## <mark> Axis in numpy

#### 2-D:
A Matrix is an example of two-dimensional data. Matrix is a collection of vectors and has a shape of (N,M) , where N is the number of vectors in it and M is the number of scalars in each vector.

The shape of the following example matrix would be(2,3).

[[1,2,3],
 [4,5,6]]

Matrix is a 2-dimensional data so it has 2 axes. 

Taking sum across axis-0 means we are summing all vectors together.

data = [[1,2,3],[4,5,6]]
np.sum(data, axis=0)

->[5, 7, 9]

Taking sum across axis-1 means, we are summing all scalars inside a vector.

data = [[1,2,3],[4,5,6]]
np.sum(data, axis=1)

->[6, 15]

### 3-D:
Similarly, 3D data is a collection of 2D data-points(matrix). The shape of 3D data would be (N,M,P). There would be N matrices of shape (M,P).

The shape of the following 3-dimensional data would be(2,2,3).

[[[1,1,1],
  [3,3,3]],
 [[2,2,2],
  [4,4,4]]]
  
Applying sum function across axis-0 means you are summing all matrices together.

Applying sum function across axis-1 means you are summing all vectors inside each metrics.

Applying sum function across axis-2 means you are summing all scalars inside each Vector.

##### Axis operations in NumPY:

    1D -> [1,2,3,4,5] -> shape(5,) [Axis 0]
    2D -> [[1,2,3,4,5],[4,5,6,7,8]] -> shape(2,5) [Axis 0, Axis 1]
    3D -> [[[1,2],[3,4],[5,6]]] -> shape(1,3,2) [Axis 0, Axis 1, Axis 2]
    
    while sorting, adding remember:
    axis 0 -columnswise
    axis 1-rowwise

##### Axis in Pandas
Similarly in Pandas, you can handle **Series as 1D** Dimensional data and **Dataframe as 2D** Dimensional data.

For example, in Dataframe, **ROWS ARE CONSIDERED ALONG AXIS=0** and **COLUMNS ALONG AXIS=1.** Applying any function across axis-0 means you are performing computation between all rows and applying a function across axis-1 means you are performing computation between all columns.

In [26]:
import numpy as np

In [27]:
#Scalar
k=np.array(4)
print("Array:",k)
print("Dim:",k.ndim)
print("Shape:",k.shape)

Array: 4
Dim: 0
Shape: ()


In [28]:
#1D vector
k=np.array([4,5])
print("Array:",k)
print("Dim:",k.ndim)
print("Shape:",k.shape)

Array: [4 5]
Dim: 1
Shape: (2,)


In [29]:
#2D matrix
k=np.array([[4,5],[6,7,]])
print("Array K:",k)
print("Dim K:",k.ndim)
print("Shape K:",k.shape,'\n')

y=np.array([[4,5]])
print("Array Y:",y)
print("Dim Y:",y.ndim)
print("Shape Y:",y.shape)

Array K: [[4 5]
 [6 7]]
Dim K: 2
Shape K: (2, 2) 

Array Y: [[4 5]]
Dim Y: 2
Shape Y: (1, 2)


In [30]:
#3D
k=np.array([[[4,5],[6,7,]]])
print("Array K:",k)
print("Dim K:",k.ndim)
print("Shape K:",k.shape,'\n')

Array K: [[[4 5]
  [6 7]]]
Dim K: 3
Shape K: (1, 2, 2) 



In [31]:
d3=np.array([[[1,1,1], [3,3,3]], [[2,2,2], [4,4,4]]])
print(d3)
"""(2,2,3)
It contains Two matrices, 
each containing TWO vectors 
which in turn containing THREE scalars each"""
print("Shape is :", d3.shape)

[[[1 1 1]
  [3 3 3]]

 [[2 2 2]
  [4 4 4]]]
Shape is : (2, 2, 3)


### <mark> Sum along axis in arrays

In [32]:
np.sum(d3, axis=0)
#Applying sum function across axis-0 means you are summing all matrices together.

array([[3, 3, 3],
       [7, 7, 7]])

In [33]:
np.sum(d3, axis=1)
#Applying sum function across axis-1 means you are summing all vectors inside each metrics.

array([[4, 4, 4],
       [6, 6, 6]])

In [34]:
np.sum(d3,axis=2)
#Applying sum function across axis-2 means you are summing all scalars inside each Vector.

array([[ 3,  9],
       [ 6, 12]])

In [4]:
import numpy as np
arr=np.arange(1,25).reshape(2,3,4)
print(arr)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [5]:
np.sum(arr,axis=0)

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [6]:
np.sum(arr,axis=1)

array([[15, 18, 21, 24],
       [51, 54, 57, 60]])

In [69]:
np.sum(arr,axis=2)

array([[10, 26, 42],
       [58, 74, 90]])

## <mark> Sorting

##### axis in np.array sorting
for numpy:

    axis 0: means through columns
    axis 1: means through rows

In [7]:
import numpy as np

a3=np.array([[[100,23,3,49]]])
a3.shape

(1, 1, 4)

In [8]:
a3.sort()
a3

array([[[  3,  23,  49, 100]]])

In [9]:
b2=np.array([[55,96,14],[23,410,96]])
print(b2)

[[ 55  96  14]
 [ 23 410  96]]


In [10]:
np.sort(b2, axis=0) #Columnwise

array([[ 23,  96,  14],
       [ 55, 410,  96]])

In [11]:
np.sort(b2, axis=1) #Row wise

array([[ 14,  55,  96],
       [ 23,  96, 410]])

In [12]:
bb2=np.array([[42,36,98]])
bb2.shape

(1, 3)

In [13]:
np.sort(bb2, axis=1)

array([[36, 42, 98]])

In [14]:
np.sort(bb2, axis=0)

array([[42, 36, 98]])

## <mark> array manipulations

    reshape
    resize
    ravel
    transpose
    
    append
    insert
    delete

In [39]:
import numpy as np
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [40]:
# Append values to the end of an array.
newArray = np.append (a, [10, 11, 12])

print(newArray)

[ 1  2  3 10 11 12]


In [41]:
# Adding column
import numpy

a = numpy.array([[1, 2, 3], [4, 5, 6]])

b = numpy.array([[400], [800]])
print("a \n",a)
print("b \n",b)
newArray = numpy.append(a, b, axis = 1)

print("New \n",newArray)

a 
 [[1 2 3]
 [4 5 6]]
b 
 [[400]
 [800]]
New 
 [[  1   2   3 400]
 [  4   5   6 800]]


In [42]:
ac = numpy.array([1, 2, 3])

newArray = numpy.insert(ac, 1, 90)
print(newArray)

[ 1 90  2  3]


In [43]:
#append a row
a = numpy.array([[1, 2, 3], [4, 5, 6]])

newArray = numpy.append(a, [[50, 60, 70]], axis = 0)
newArray

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [50, 60, 70]])

In [44]:
#Append NumPy array to another
a = numpy.array([1, 2, 3, 4, 5])

b = numpy.array([10, 20, 30, 40, 50])

newArray = numpy.append(a, b)

print("The new array = ", newArray)

The new array =  [ 1  2  3  4  5 10 20 30 40 50]


In [45]:
import numpy

a = numpy.array([11, 22, 33])

newArray = numpy.delete(a, 1, axis = 0)
print(newArray)

[11 33]


In [46]:
#@if you dont know the index
a = numpy.array([11, 22, 33])

newArray = numpy.delete(a, np.where(a==22), axis = 0)
print(newArray)

[11 33]


In [47]:
#Delet a row
a = numpy.array([[1, 2, 3], [4, 5, 6], [10, 20, 30]])

newArray = numpy.delete(a, 1, axis = 0)
print(newArray)

[[ 1  2  3]
 [10 20 30]]


### <mark> Applying function to all array elements

Unlike in list(where iteration must be done), a function can be directly applied on all elements of an array

In [64]:
import numpy

addition = lambda x: x + 2

a = numpy.array([1, 2, 3, 4, 5, 6])

print("Array after addition function: ", addition(a))

Array after addition function:  [3 4 5 6 7 8]


### <mark> Iterating through an array

    - using for loop
    - using for loop and arr.ravel()
    - using np.nditer(array)  :Efficient multi-dimensional iterator object to iterate over arrays
    - using np.ndenumerate(arr)  :helps get index of element while interating

In [77]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
    for y in x:
        for z in y:
              print(z,end=".")

1.2.3.4.5.6.7.8.9.10.11.12.

In [78]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in arr.ravel():
    print(x,end=".")

1.2.3.4.5.6.7.8.

In [80]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x, end=".")

1.2.3.4.5.6.7.8.

In [7]:
# iterating through different stepsize
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr[:, ::2])
for x in np.nditer(arr[:, ::2]):
    print(x)

[[1 3]
 [5 7]]
1
3
5
7


In [76]:
arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [81]:
arr = np.array([[15, 26], [50, 60]])

for idx, x in np.ndenumerate(arr):
    print(idx, x)

(0, 0) 15
(0, 1) 26
(1, 0) 50
(1, 1) 60


## <mark> Joining Arrays

    concatenate
    hstack
    vstack
    
"""We pass a sequence of arrays that we want to join to the concatenate() function, 
along with the axis. 
If axis is not explicitly passed, it is taken as 0."""
    
"""
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.
We can concatenate two 1-D arrays along the second axis which would result in putting 
them one over the other, ie. stacking.
We pass a sequence of arrays that we want to join to the stack() method along with the axis. 
If axis is not explicitly passed it is taken as 0.
"""

In [82]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [83]:
arrr=arr1+arr2
arrr
#This is addition not concatenation

array([5, 7, 9])

In [88]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1,'\n', arr2)

arrc0 = np.concatenate((arr1, arr2), axis=0)
print('concatenated along axis=0 \n',arrc0)

print('Concat along axis=1 not possible')

arrs=np.hstack((arr1,arr2))
print('Hstack \n',arrs)

arrv=np.vstack((arr1,arr2))
print('Vstack \n',arrv)


arrd=np.dstack((arr1,arr2))
print('Dstack \n',arrd)

[1 2 3] 
 [4 5 6]
concatenated along axis=0 
 [1 2 3 4 5 6]
COncat along axis=1 not possible
Hstack 
 [1 2 3 4 5 6]
Vstack 
 [[1 2 3]
 [4 5 6]]
Dstack 
 [[[1 4]
  [2 5]
  [3 6]]]


In [86]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(arr1, '\n\n', arr2)

arrc0 = np.concatenate((arr1, arr2), axis=0)
print('concatenated along axis=0 \n',arrc0)

arrc1 = np.concatenate((arr1, arr2), axis=1)
print('concatenated along axis=1 \n',arrc1)

arrs=np.hstack((arr1,arr2))
print('Hstack: stacks arrays horizontally, columnwise \n',arrs)

arrv=np.vstack((arr1,arr2))
print('Vstack: stacks arrays horizontally, rowwise \n',arrv)

# arrd=np.dstack((arr1,arr2))
# print('Dstack \n',arrd)

[[1 2]
 [3 4]] 

 [[5 6]
 [7 8]]
concatenated along axis=0 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
concatenated along axis=1 
 [[1 2 5 6]
 [3 4 7 8]]
Hstack: stacks arrays horizontally, columnwise 
 [[1 2 5 6]
 [3 4 7 8]]
Vstack: stacks arrays horizontally, rowwise 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [90]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1, '\n')
print(arr2)

arr = np.stack((arr1, arr2), axis=0)
print('stack along axis 0 \n', arr)

arr = np.stack((arr1, arr2),axis=1)
print('stack along axis 1 \n', arr)

arr = np.hstack((arr1, arr2))
print('hstack \n', arr)

arr = np.vstack((arr1, arr2))
print('vstack \n', arr)

[1 2 3] 

[4 5 6]
stack along axis 0 
 [[1 2 3]
 [4 5 6]]
stack along axis 1 
 [[1 4]
 [2 5]
 [3 6]]
hstack 
 [1 2 3 4 5 6]
vstack 
 [[1 2 3]
 [4 5 6]]


### <mark> spliting arrays: hsplit vsplit

np.split(arr,n) - Split an array into multiple sub-arrays of euqal size

np.array_split(arr,n) - Split an array in sub-arrays of (nearly) identical size

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits. The return value is an array containing n arrays.

In [11]:
arr = np.array([1, 2, 3, 4, 5, 6])
np.split(arr, 3)
#Split an array into multiple sub-arrays of euqal size

[array([1, 2]), array([3, 4]), array([5, 6])]

In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 4)
print(newarr)

#If you split an array into 4 arrays, 
#you can access them from the result just like any array element:
print(newarr[1])

[array([1, 2]), array([3, 4]), array([5]), array([6])]
[3 4]


In [93]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [95]:
"""Use the hsplit() method to split the 2-D array into three 2-D arrays along rows.
hsplit() is opposite of hstack()
Similar alternates to vstack() and dstack() are available as vsplit() and dsplit()."""

# Split the 2-D array into three 2-D arrays along rows.

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
print('original \n', arr)
newarr = np.array_split(arr, 3, axis=1)
print('new \n', newarr)

original 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
new 
 [array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]
